### ISSUE TITLE
get error using function trade()

### ISSUE THREAD

**Issue by moku23** [David-Woroniuk/Medium-Articles#1]
Hello, I'm getting an error when using a function trade()

> UnboundLocalError: local variable 'i' referenced before assignment

function are called by: 
`buy_states, sell_states, total_gains, RoC = trade(strategy_one, strategy_one['close'], strategy_one['trigger'])`

and was returned by: `---> 58     consolidated_position = (capital + inventory * price_change[i])`
What I need to check?

**Comment by David-Woroniuk** [comment]
Hi Moku - this is due to misalignment of dates in the data called from the AlphaVantage API and twitter_data.csv.

As you will notice, strategy_one, strategy_two strategy_three and strategy_four are all empty DataFrames. If you require the twitter data/market data to replicate, I am happy to discuss in a private message.
